
.PHONY: clean
.PHONY: helloworld

helloworld: helloworld.c
	$(CC) -g -Wall $(CFLAGS) $(LDFLAGS) $< -o $@

clean:
	-rm helloworld
        
#### NOTE: Makefile requires a tab character for indentation. Spaces will not work. ####

